// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "6191d2bf-873d-4bef-a8c6-6129fdb866a4";


const char SSID[]               = "TALHATA";    // Network SSID (name)
const char PASS[]               = "fran262218";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "1O7I6RQBW0XKE06RKWLT";    // Secret device password

//carro


void onMsgChange();
void onIrChange();
void onPreciChange();
void onGpsChange();

String msg;
float dISTANCIA;
int preci;
CloudLocation gps;
bool ir;
float frentee;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(msg, READWRITE, ON_CHANGE, onMsgChange);
  ArduinoCloud.addProperty(dISTANCIA, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(preci, READWRITE, ON_CHANGE, onPreciChange);
  ArduinoCloud.addProperty(ir, READWRITE, ON_CHANGE, onIrChange, 5);
  ArduinoCloud.addProperty(gps, READWRITE, ON_CHANGE, onGpsChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
